services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  app:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    networks:
      - app_net

  web:
    build: ./web
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
